### ISSUE TITLE
关于设置组合键后无法使用

### ISSUE THREAD

**Issue by chaos-41424** [RiverYale/Userscripts#2]
作者，你好！近日插件更新到了5.3，设置好组合键后，在B站播放视频时，以下圈出来的几个组合键无法使用，但在B站直播中能正常使用（插件版本5.2的时候，B站播放视频时组合键能正常使用）。无法使用的几个组合键的功能跟B站视频提供的快捷键有冲突。
![Snipaste_2024-04-12_01-06-17](https://github.com/RiverYale/Userscripts/assets/49650006/1e34f7c0-8a02-49ab-b355-c6ac296eaf0e)

**Comment by RiverYale** [comment]
已更新到5.4版本

**Comment by RiverYale** [comment]
已更新到5.4版本，完善了判断。还有```77 == e.keyCode```这样的判断只要按下<kbd>M</kbd>就会触发，无论是否按了组合键。如果想组合键不被触发可以改成```!e.shiftKey && 77 == e.keyCode```，这样按下<kbd>shift + M</kbd>就不会触发了，其他组合键同理。

**Comment by chaos-41424** [comment]
感谢大佬！嘭嘭嘭
